//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDE
{


    public partial class Login
    {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox emailInput;

        protected global::System.Web.UI.WebControls.TextBox passwordInput;

        protected global::System.Web.UI.WebControls.Button loginButton;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl errorMessage;
    }
}
